name = "car-lot-email-worker"
main = "src/index.js"
compatibility_date = "2025-10-25"

[[email]]
binding = "SEND_EMAIL"
destination_address = "noreply@danscarlot.turneratlanta.com"

[vars]
MAILCHANNELS_API_URL = "https://api.mailchannels.net/tx/v1/send"

[[routes]]
pattern = "https://danscarlot.turneratlanta.com/api/send-email"
zone_name = "turneratlanta.com"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
